# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.TextField(),
        ),
    ]
