# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20170810_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='paper.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
